services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - server

  web:
    build: 
      context: .
      dockerfile: frontend/Dockerfile.prod
    cpus: 0.5

  server:
    build: ./backend
    environment:
      - FLASK_ENV=production