# Use a slimmer base image
FROM python:3-slim

# Set work directory
WORKDIR /app

# Set environment variables
ENV FLASK_APP=app.py \
    FLASK_ENV=development \
    # Python won’t try to write .pyc files on the container
    PYTHONDONTWRITEBYTECODE=1 \
    # Python outputs all messages directly to the terminal without buffering
    PYTHONUNBUFFERED=1

# Install dependencies
# Copy only requirements, to cache them in docker layer
COPY ./requirements.txt .
# Install dependencies with no cache to save space
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["python3", "app.py"]
