name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Notify EC2 webhook server
      env:
        PI_WEBHOOK_URL: http://3.16.222.159:9000/hooks/deploy
      run: |
        curl -X POST "$PI_WEBHOOK_URL"

# Yes i know this is horribly unsecure but the scope right now is not too large and its still in development
